apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
spec:
  template:
    spec:
      containers:
      - name: app-test
        resources:
          limits:
            memory: 1Gi